Silence "mv" and eliminate some "cd" commands

diff --git a/src/bin/sage-spkg b/src/bin/sage-spkg
--- a/src/bin/sage-spkg
+++ b/src/bin/sage-spkg
@@ -572,7 +572,7 @@ fi
 if [ "$USE_LOCAL_SCRIPTS" = yes ]; then
     echo "Setting up build directory for $PKG_NAME"
     cp -Rp "$PKG_SCRIPTS" "$PKG_NAME"
-    cd "$PKG_NAME"
+    cd "$PKG_NAME" || exit $?
 else
     echo "Extracting package $PKG_SRC"
     ls -l "$PKG_SRC"
@@ -585,22 +585,21 @@ if [ $? -ne 0 ]; then
 fi
 
 if [ "$USE_LOCAL_SCRIPTS" = yes ]; then
-    mv "${PKG_NAME_UPSTREAM%.tar*}" src
-    cd ..
+    mv 2>/dev/null "${PKG_NAME_UPSTREAM%.tar*}" src
     echo "Finished set up"
 else
     echo "Finished extraction"
+
+    cd "$PKG_NAME"
+    if [ $? -ne 0 ]; then
+        echo >&2 "Error: after extracting, the directory $PKG_NAME does not exist"
+        exit 1
+    fi
 fi
 
 ##################################################################
 # The package has been extracted, prepare for installation
 ##################################################################
-
-cd "$PKG_NAME"
-if [ $? -ne 0 ]; then
-    echo >&2 "Error: after extracting, the directory $PKG_NAME does not exist"
-    exit 1
-fi
 
 # When there is no spkg-install, assume the "spkg" is a tarball not
 # specifically made for Sage.  Since we want it to be as easy as
